[unstable]
#build-std = ["std", "panic_abort", "core", "alloc"]
#build-std-features = ["panic_immediate_abort"]

[build]
#jobs = 1
#target = "x86_64-pc-windows-msvc"
#rustflags = ["--cfg=web_sys_unstable_apis", "-Zlocation-detail=none"]